name: Deploy

on:
  push:
    branches:
    - master
  pull_request: {}

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'no-deploy') || github.event_name == 'pull_request'"
    runs-on: ubuntu-latest
    steps:
    - uses: gradebook/actions/actions/setup@master
    - name: Install Dependencies
      run: yarn install --frozen-lockfile
    - name: Lint
      run: yarn lint
    - name: Compile CSS
      run: |
        yarn css
        yarn minify
      env:
        NODE_ENV: production
    - name: Generate JSON objects
      run: node build.js
    - name: Deploy
      if: "github.event_name != 'pull_request'"
      run: |
        export NETLIFY_DEPLOY_TITLE=$(git log -1 --format="%s (%h)")
        node node_modules/@gradebook/netlify-deploy/lib/recipe.js
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_DEPLOY_DIR: dist
        NETLIFY_PRODUCTION_DEPLOY: 'true'
    - name: Reload
      if: "github.event_name != 'pull_request'"
      run: |
        export WEBHOOK_DATA=$(echo '{"timestamp": __}' | sed s/__/`date +"%s"`/)
        yarn release-utils hook
      env:
        HOOK_TYPE: generic
        WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
