name: Update pages

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: |
        echo "$GITHUB____ACTOR"
        echo "$GITHUB____REF"
      env:
        GITHUB____ACTOR: ${{ github.actor }}
        GITHUB____REF: ${{ github.ref }}
    - name: Update docs
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git remote rm origin || true
        git remote add origin "https://x-access-token:${TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        git fetch origin gh-pages:gh-pages
        git fetch origin master:master
        git checkout master
        yarn install --production
        yarn css
        node build.js
        cp -r site built
        git checkout gh-pages
        mv built/* . -f
        git add .
        git commit -m ":rocket: update docs" || echo "No changes here 🧹"
        git push -u origin gh-pages
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
