name: Update pages

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'master'
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo "$GITHUB____ACTOR"
      env:
        GITHUB____ACTOR: ${{ github.actor }}
    - name: Update docs
      run: |
        yarn install
        node build.js
        cd docs
        yarn install
        yarn css
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git remote rm origin || true
        git remote add origin "https://x-access-token:${TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        git add docs
        git commit -m ":rocket: || echo "No changes here 🧹"
        git push origin master
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
